# Generated by Django 5.1.4 on 2024-12-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('theme', models.CharField(choices=[('green', 'Personal'), ('blue', 'Business'), ('orange', 'Family'), ('purple', 'Important'), ('red', 'Holiday')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
