# Generated by Django 5.1.5 on 2025-02-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0002_reservation_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
