# Generated by Django 5.1.4 on 2024-12-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0002_specialist_booking_workingschedule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workingschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='day_of_weeks',
            field=models.CharField(default='Monday', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='workingschedule',
            name='day_of_week',
        ),
    ]
