# Generated by Django 5.1.4 on 2024-12-23 16:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0003_alter_workingschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingschedule',
            name='day_of_weeks',
        ),
        migrations.AddField(
            model_name='workingschedule',
            name='days_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
