# Generated by Django 5.1.5 on 2025-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0003_alter_reservation_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
