# Generated by Django 5.1.5 on 2025-02-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0004_alter_reservation_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='total_doctor_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
