# Generated by Django 5.1.5 on 2025-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0005_doctor_total_doctor_earning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='moderator_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('can_view_statistics', models.BooleanField(default=False)),
                ('can_view_calendar', models.BooleanField(default=False)),
                ('can_view_users', models.BooleanField(default=False)),
                ('can_view_services', models.BooleanField(default=False)),
                ('can_view_notification', models.BooleanField(default=False)),
                ('can_view_treatment', models.BooleanField(default=False)),
                ('can_view_cashback', models.BooleanField(default=False)),
                ('can_view_pages', models.BooleanField(default=False)),
                ('can_view_discount_code', models.BooleanField(default=False)),
                ('can_view_doctors', models.BooleanField(default=False)),
                ('can_view_history', models.BooleanField(default=False)),
                ('can_view_moderator', models.BooleanField(default=False)),
                ('can_view_laser', models.BooleanField(default=False)),
                ('can_view_payment_acceptance', models.BooleanField(default=False)),
                ('can_view_doctor_payment', models.BooleanField(default=False)),
                ('can_view_excel', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
