# Generated by Django 5.1.5 on 2025-02-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0006_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='moderator',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('inactive', 'Deaktiv')], default='active', max_length=8),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
