# Generated by Django 5.1.5 on 2025-02-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0009_user_firebase_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_created', 'İstifadəçi əlavə etdi'), ('reservation_completed', 'Ödəniş qəbul etdi'), ('laser_changed', 'Lazer atış istifadəsi bölməsində dəyişikliklər etdi'), ('reservation_created', 'Müştərini rezervasiya etdi')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='lalisa.moderator')),
            ],
        ),
    ]
