# Generated by Django 5.1.5 on 2025-04-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lalisa', '0011_user_otp_code_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
